import type {
  Agent,
  AgentStatus,
  AlertItem,
  ApiKey,
  Approval,
  ApprovalRule,
  AuditEntry,
  Integration,
  KpiMetric,
  Session,
  Tenant,
  Tool,
  User,
  Webhook,
  WebhookEvent,
} from "./types"

export const agents: Agent[] = [
  {
    id: "agt-001",
    name: "Support Assistant",
    role: "Customer Support",
    description: "Handles tier-1 customer support tickets and FAQs.",
    instructions:
      "You are a helpful support agent. Resolve customer issues using the knowledge base and escalate when needed.",
    model: "gpt-4o",
    temperature: 0.4,
    maxTokens: 2048,
    timeout: 30,
    status: "active",
    team: "Support",
    domain: "Customer Service",
    tenant: "acme",
    owner: "Sarah Chen",
    lastActivity: "2026-09-12T09:42:00Z",
    tags: ["support", "tier-1", "faq"],
    tools: ["zendesk", "knowledge-base", "slack"],
    handoffs: ["agt-004"],
    versions: [
      {
        id: "v3",
        version: 3,
        createdAt: "2026-09-10T10:00:00Z",
        author: "Sarah Chen",
        summary: "Added escalation handoff to billing agent",
        diff: "+ handoffs: [agt-004]",
      },
      {
        id: "v2",
        version: 2,
        createdAt: "2026-09-01T10:00:00Z",
        author: "Sarah Chen",
        summary: "Lowered temperature to 0.4",
        diff: "- temperature: 0.7\n+ temperature: 0.4",
      },
    ],
    metrics: {
      avgResponseTime: 1.8,
      successRate: 96.4,
      costPerSession: 0.12,
      sessions: 1842,
      satisfaction: 4.7,
    },
  },
  {
    id: "agt-002",
    name: "Billing Analyst",
    role: "Finance",
    description: "Analyzes invoices and flags billing anomalies.",
    instructions:
      "Review billing data, detect anomalies, and generate cost reports.",
    model: "gpt-4",
    temperature: 0.2,
    maxTokens: 4096,
    timeout: 60,
    status: "active",
    team: "Finance",
    domain: "Billing",
    tenant: "acme",
    owner: "Jamik Tashpulatov",
    lastActivity: "2026-09-12T08:15:00Z",
    tags: ["billing", "finance", "reports"],
    tools: ["stripe", "postgres", "sheets"],
    handoffs: [],
    versions: [
      {
        id: "v1",
        version: 1,
        createdAt: "2026-08-20T10:00:00Z",
        author: "Jamik Tashpulatov",
        summary: "Initial version",
        diff: "+ initial",
      },
    ],
    metrics: {
      avgResponseTime: 3.2,
      successRate: 91.8,
      costPerSession: 0.45,
      sessions: 640,
      satisfaction: 4.2,
    },
  },
  {
    id: "agt-003",
    name: "Data Pipeline Runner",
    role: "Data Engineering",
    description: "Orchestrates ETL jobs and monitors data quality.",
    instructions: "Run and monitor ETL pipelines, report failures.",
    model: "gpt-4o",
    temperature: 0.1,
    maxTokens: 2048,
    timeout: 120,
    status: "idle",
    team: "Data",
    domain: "ETL",
    tenant: "globex",
    owner: "David Kim",
    lastActivity: "2026-09-11T22:30:00Z",
    tags: ["etl", "data", "pipeline"],
    tools: ["airflow", "postgres", "s3"],
    handoffs: [],
    versions: [
      {
        id: "v1",
        version: 1,
        createdAt: "2026-08-15T10:00:00Z",
        author: "David Kim",
        summary: "Initial version",
        diff: "+ initial",
      },
    ],
    metrics: {
      avgResponseTime: 5.1,
      successRate: 88.2,
      costPerSession: 0.9,
      sessions: 312,
      satisfaction: 3.9,
    },
  },
  {
    id: "agt-004",
    name: "Escalation Router",
    role: "Orchestrator",
    description: "Routes complex tickets to specialized agents.",
    instructions:
      "Classify incoming requests and hand off to the appropriate specialist.",
    model: "gpt-4o",
    temperature: 0.3,
    maxTokens: 1024,
    timeout: 15,
    status: "error",
    team: "Support",
    domain: "Routing",
    tenant: "acme",
    owner: "Sarah Chen",
    lastActivity: "2026-09-12T09:50:00Z",
    tags: ["router", "orchestrator"],
    tools: ["zendesk", "slack"],
    handoffs: ["agt-001", "agt-002"],
    versions: [
      {
        id: "v2",
        version: 2,
        createdAt: "2026-09-08T10:00:00Z",
        author: "Sarah Chen",
        summary: "Added billing handoff",
        diff: "+ handoffs: [agt-002]",
      },
    ],
    metrics: {
      avgResponseTime: 0.9,
      successRate: 82.5,
      costPerSession: 0.08,
      sessions: 2210,
      satisfaction: 4.0,
    },
  },
  {
    id: "agt-005",
    name: "Content Writer",
    role: "Marketing",
    description: "Drafts blog posts and marketing copy.",
    instructions: "Write engaging marketing content in the brand voice.",
    model: "gpt-4",
    temperature: 0.8,
    maxTokens: 4096,
    timeout: 45,
    status: "stalled",
    team: "Marketing",
    domain: "Content",
    tenant: "globex",
    owner: "Maria Garcia",
    lastActivity: "2026-09-10T14:00:00Z",
    tags: ["content", "marketing", "copy"],
    tools: ["cms", "sheets"],
    handoffs: [],
    versions: [
      {
        id: "v1",
        version: 1,
        createdAt: "2026-08-25T10:00:00Z",
        author: "Maria Garcia",
        summary: "Initial version",
        diff: "+ initial",
      },
    ],
    metrics: {
      avgResponseTime: 4.4,
      successRate: 90.1,
      costPerSession: 0.6,
      sessions: 480,
      satisfaction: 4.5,
    },
  },
  {
    id: "agt-006",
    name: "Compliance Reviewer",
    role: "Legal",
    description: "Reviews documents for regulatory compliance.",
    instructions: "Check documents against SOC2 and GDPR requirements.",
    model: "gpt-4",
    temperature: 0.1,
    maxTokens: 8192,
    timeout: 90,
    status: "archived",
    team: "Legal",
    domain: "Compliance",
    tenant: "acme",
    owner: "Priya Singh",
    lastActivity: "2026-08-30T11:00:00Z",
    tags: ["legal", "compliance", "gdpr"],
    tools: ["postgres", "s3"],
    handoffs: [],
    versions: [
      {
        id: "v1",
        version: 1,
        createdAt: "2026-08-01T10:00:00Z",
        author: "Priya Singh",
        summary: "Initial version",
        diff: "+ initial",
      },
    ],
    metrics: {
      avgResponseTime: 6.2,
      successRate: 94.0,
      costPerSession: 1.2,
      sessions: 150,
      satisfaction: 4.6,
    },
  },
]

export const tools: Tool[] = [
  {
    id: "zendesk",
    name: "Zendesk",
    category: "Support",
    description: "Customer support ticketing system.",
    status: "connected",
    latency: 120,
    scopes: ["tickets:read", "tickets:write"],
    rateLimit: "100 req/min",
  },
  {
    id: "stripe",
    name: "Stripe",
    category: "Billing",
    description: "Payment processing and invoicing.",
    status: "connected",
    latency: 180,
    scopes: ["invoices:read", "charges:read"],
    rateLimit: "50 req/min",
  },
  {
    id: "postgres",
    name: "PostgreSQL",
    category: "Database",
    description: "Primary application database.",
    status: "connected",
    latency: 45,
    scopes: ["read", "write"],
    rateLimit: "unlimited",
  },
  {
    id: "slack",
    name: "Slack",
    category: "Communication",
    description: "Team messaging and notifications.",
    status: "degraded",
    latency: 900,
    scopes: ["messages:write"],
    rateLimit: "20 req/min",
  },
  {
    id: "airflow",
    name: "Airflow",
    category: "Data",
    description: "Workflow orchestration.",
    status: "connected",
    latency: 200,
    scopes: ["dag:trigger", "dag:read"],
    rateLimit: "10 req/min",
  },
  {
    id: "s3",
    name: "Amazon S3",
    category: "Storage",
    description: "Object storage for artifacts.",
    status: "disconnected",
    latency: 0,
    scopes: ["read", "write"],
    rateLimit: "unlimited",
  },
  {
    id: "cms",
    name: "Contentful",
    category: "CMS",
    description: "Headless content management.",
    status: "connected",
    latency: 150,
    scopes: ["content:read", "content:write"],
    rateLimit: "30 req/min",
  },
  {
    id: "sheets",
    name: "Google Sheets",
    category: "Productivity",
    description: "Spreadsheet read/write.",
    status: "connected",
    latency: 300,
    scopes: ["spreadsheets:read", "spreadsheets:write"],
    rateLimit: "60 req/min",
  },
  {
    id: "knowledge-base",
    name: "Knowledge Base",
    category: "Support",
    description: "Internal documentation search.",
    status: "connected",
    latency: 80,
    scopes: ["search"],
    rateLimit: "unlimited",
  },
]

export const sessions: Session[] = [
  {
    id: "sess-1001",
    agentId: "agt-001",
    agentName: "Support Assistant",
    status: "completed",
    duration: 42,
    cost: 0.18,
    timestamp: "2026-09-12T09:40:00Z",
    tenant: "acme",
    user: "customer@example.com",
    tags: ["refund", "urgent"],
    turns: [
      {
        id: "t1",
        role: "user",
        content: "I need a refund for my last order.",
        duration: 0,
        timestamp: "2026-09-12T09:40:00Z",
        status: "ok",
      },
      {
        id: "t2",
        role: "tool",
        content: "Searched knowledge base for refund policy.",
        tool: "knowledge-base",
        duration: 1.2,
        timestamp: "2026-09-12T09:40:02Z",
        status: "ok",
      },
      {
        id: "t3",
        role: "assistant",
        content: "I can help with that. Your refund has been initiated.",
        duration: 2.1,
        timestamp: "2026-09-12T09:40:05Z",
        status: "ok",
      },
    ],
    artifacts: [{ name: "refund-receipt.pdf", type: "pdf", size: "24 KB" }],
  },
  {
    id: "sess-1002",
    agentId: "agt-002",
    agentName: "Billing Analyst",
    status: "running",
    duration: 180,
    cost: 0.62,
    timestamp: "2026-09-12T09:30:00Z",
    tenant: "acme",
    user: "finance@example.com",
    tags: ["monthly-report"],
    turns: [
      {
        id: "t1",
        role: "user",
        content: "Generate the September billing report.",
        duration: 0,
        timestamp: "2026-09-12T09:30:00Z",
        status: "ok",
      },
      {
        id: "t2",
        role: "tool",
        content: "Querying Stripe invoices.",
        tool: "stripe",
        duration: 3.4,
        timestamp: "2026-09-12T09:30:05Z",
        status: "ok",
      },
    ],
    artifacts: [],
  },
  {
    id: "sess-1003",
    agentId: "agt-004",
    agentName: "Escalation Router",
    status: "failed",
    duration: 8,
    cost: 0.02,
    timestamp: "2026-09-12T09:20:00Z",
    tenant: "acme",
    user: "system",
    tags: ["routing"],
    turns: [
      {
        id: "t1",
        role: "user",
        content: "Route ticket #4821 to billing.",
        duration: 0,
        timestamp: "2026-09-12T09:20:00Z",
        status: "ok",
      },
      {
        id: "t2",
        role: "tool",
        content: "Failed to reach Zendesk API.",
        tool: "zendesk",
        duration: 5.0,
        timestamp: "2026-09-12T09:20:05Z",
        status: "error",
      },
    ],
    artifacts: [],
  },
  {
    id: "sess-1004",
    agentId: "agt-003",
    agentName: "Data Pipeline Runner",
    status: "completed",
    duration: 300,
    cost: 1.4,
    timestamp: "2026-09-11T22:00:00Z",
    tenant: "globex",
    user: "data@example.com",
    tags: ["etl", "nightly"],
    turns: [
      {
        id: "t1",
        role: "user",
        content: "Run the nightly ETL pipeline.",
        duration: 0,
        timestamp: "2026-09-11T22:00:00Z",
        status: "ok",
      },
      {
        id: "t2",
        role: "tool",
        content: "Triggered Airflow DAG.",
        tool: "airflow",
        duration: 2.0,
        timestamp: "2026-09-11T22:00:03Z",
        status: "ok",
      },
      {
        id: "t3",
        role: "assistant",
        content: "Pipeline completed successfully. 1.2M rows processed.",
        duration: 4.0,
        timestamp: "2026-09-11T22:05:00Z",
        status: "ok",
      },
    ],
    artifacts: [{ name: "etl-log.txt", type: "txt", size: "1.2 MB" }],
  },
  {
    id: "sess-1005",
    agentId: "agt-005",
    agentName: "Content Writer",
    status: "pending",
    duration: 0,
    cost: 0,
    timestamp: "2026-09-12T10:00:00Z",
    tenant: "globex",
    user: "marketing@example.com",
    tags: ["blog"],
    turns: [],
    artifacts: [],
  },
]

export const approvals: Approval[] = [
  {
    id: "appr-001",
    action: "Refund customer $250",
    agentId: "agt-001",
    agentName: "Support Assistant",
    risk: "medium",
    deadline: "2026-09-12T12:00:00Z",
    status: "pending",
    context: "Customer reported duplicate charge on order #8842.",
    justification: "Duplicate charge confirmed in Stripe logs.",
    impact: "Refund of $250 to customer account.",
    amount: 250,
    requestedBy: "Support Assistant",
    decisions: [],
  },
  {
    id: "appr-002",
    action: "Delete production database table",
    agentId: "agt-003",
    agentName: "Data Pipeline Runner",
    risk: "high",
    deadline: "2026-09-12T11:00:00Z",
    status: "pending",
    context: "Requested DROP TABLE on staging_events.",
    justification: "Table is stale and no longer used.",
    impact: "Permanent deletion of 4.2M rows.",
    requestedBy: "Data Pipeline Runner",
    decisions: [],
  },
  {
    id: "appr-003",
    action: "Send marketing email to 10k users",
    agentId: "agt-005",
    agentName: "Content Writer",
    risk: "low",
    deadline: "2026-09-13T09:00:00Z",
    status: "approved",
    context: "Monthly newsletter campaign.",
    justification: "Scheduled campaign approved by marketing lead.",
    impact: "Email sent to 10,000 subscribers.",
    requestedBy: "Content Writer",
    decisions: [
      {
        by: "Maria Garcia",
        action: "approved",
        comment: "Looks good.",
        at: "2026-09-12T08:30:00Z",
      },
    ],
  },
  {
    id: "appr-004",
    action: "Call external API with PII",
    agentId: "agt-002",
    agentName: "Billing Analyst",
    risk: "high",
    deadline: "2026-09-12T10:30:00Z",
    status: "escalated",
    context: "Sending customer PII to third-party enrichment API.",
    justification: "Needed for fraud detection.",
    impact: "PII of 500 customers shared externally.",
    requestedBy: "Billing Analyst",
    decisions: [
      {
        by: "Jamik Tashpulatov",
        action: "escalated",
        comment: "Needs security review.",
        at: "2026-09-12T09:00:00Z",
      },
    ],
  },
]

export const approvalRules: ApprovalRule[] = [
  {
    id: "rule-001",
    agentId: "agt-001",
    agentName: "Support Assistant",
    actionTypes: ["refund", "delete"],
    threshold: 100,
    autoApprove: false,
    escalation: "support-lead@example.com",
    escalationTimeout: 60,
  },
  {
    id: "rule-002",
    agentId: "agt-002",
    agentName: "Billing Analyst",
    actionTypes: ["external-api", "refund"],
    threshold: 500,
    autoApprove: false,
    escalation: "finance-lead@example.com",
    escalationTimeout: 30,
  },
  {
    id: "rule-003",
    agentId: "agt-003",
    agentName: "Data Pipeline Runner",
    actionTypes: ["delete", "schema-change"],
    threshold: 0,
    autoApprove: false,
    escalation: "data-lead@example.com",
    escalationTimeout: 15,
  },
]

export const users: User[] = [
  {
    id: "usr-001",
    name: "Sarah Chen",
    email: "sarah@acme.com",
    role: "admin",
    tenant: "acme",
    lastLogin: "2026-09-12T09:00:00Z",
  },
  {
    id: "usr-002",
    name: "Jamik Tashpulatov",
    email: "jamik@acme.com",
    role: "editor",
    tenant: "acme",
    lastLogin: "2026-09-12T08:45:00Z",
  },
  {
    id: "usr-003",
    name: "David Kim",
    email: "david@globex.com",
    role: "editor",
    tenant: "globex",
    lastLogin: "2026-09-11T20:00:00Z",
  },
  {
    id: "usr-004",
    name: "Maria Garcia",
    email: "maria@globex.com",
    role: "viewer",
    tenant: "globex",
    lastLogin: "2026-09-11T18:30:00Z",
  },
  {
    id: "usr-005",
    name: "Priya Singh",
    email: "priya@acme.com",
    role: "viewer",
    tenant: "acme",
    lastLogin: "2026-09-10T15:00:00Z",
  },
]

export const tenants: Tenant[] = [
  {
    id: "acme",
    name: "Acme Corp",
    maxAgents: 20,
    maxSessionsPerDay: 5000,
    monthlyBudget: 10000,
    logo: "A",
    color: "#6366f1",
    domain: "acme.presk.io",
  },
  {
    id: "globex",
    name: "Globex Inc",
    maxAgents: 10,
    maxSessionsPerDay: 2000,
    monthlyBudget: 5000,
    logo: "G",
    color: "#10b981",
    domain: "globex.presk.io",
  },
]

export const integrations: Integration[] = [
  {
    id: "int-001",
    name: "Zendesk",
    category: "Support",
    description: "Customer support ticketing.",
    status: "up",
    latency: 120,
    endpoint: "https://api.zendesk.com/v2",
    scopes: ["tickets:read", "tickets:write"],
    rateLimit: "100 req/min",
  },
  {
    id: "int-002",
    name: "Stripe",
    category: "Billing",
    description: "Payment processing.",
    status: "up",
    latency: 180,
    endpoint: "https://api.stripe.com/v1",
    scopes: ["invoices:read"],
    rateLimit: "50 req/min",
  },
  {
    id: "int-003",
    name: "Slack",
    category: "Communication",
    description: "Team messaging.",
    status: "degraded",
    latency: 900,
    endpoint: "https://slack.com/api",
    scopes: ["messages:write"],
    rateLimit: "20 req/min",
  },
  {
    id: "int-004",
    name: "Airflow",
    category: "Data",
    description: "Workflow orchestration.",
    status: "up",
    latency: 200,
    endpoint: "https://airflow.internal/api",
    scopes: ["dag:trigger"],
    rateLimit: "10 req/min",
  },
  {
    id: "int-005",
    name: "Custom CRM",
    category: "CRM",
    description: "Internal customer records.",
    status: "down",
    latency: 0,
    endpoint: "https://crm.internal/api",
    scopes: ["records:read"],
    rateLimit: "unlimited",
  },
]

export const webhooks: Webhook[] = [
  {
    id: "wh-001",
    url: "https://acme.com/hooks/session",
    events: ["session.completed", "session.failed"],
    status: "active",
    lastSent: "2026-09-12T09:40:00Z",
    successRate: 99.2,
  },
  {
    id: "wh-002",
    url: "https://acme.com/hooks/approval",
    events: ["approval.pending"],
    status: "active",
    lastSent: "2026-09-12T09:20:00Z",
    successRate: 100,
  },
  {
    id: "wh-003",
    url: "https://globex.com/hooks/error",
    events: ["agent.error"],
    status: "disabled",
    lastSent: "2026-09-10T14:00:00Z",
    successRate: 87.5,
  },
]

export const webhookEvents: WebhookEvent[] = [
  {
    id: "we-001",
    webhookId: "wh-001",
    event: "session.completed",
    status: "success",
    timestamp: "2026-09-12T09:40:00Z",
    payload: '{"sessionId":"sess-1001","status":"completed"}',
  },
  {
    id: "we-002",
    webhookId: "wh-001",
    event: "session.failed",
    status: "success",
    timestamp: "2026-09-12T09:20:00Z",
    payload: '{"sessionId":"sess-1003","status":"failed"}',
  },
  {
    id: "we-003",
    webhookId: "wh-002",
    event: "approval.pending",
    status: "success",
    timestamp: "2026-09-12T09:20:00Z",
    payload: '{"approvalId":"appr-001"}',
  },
  {
    id: "we-004",
    webhookId: "wh-003",
    event: "agent.error",
    status: "failed",
    timestamp: "2026-09-10T14:00:00Z",
    payload: '{"agentId":"agt-004","error":"timeout"}',
  },
]

export const auditLog: AuditEntry[] = [
  {
    id: "aud-001",
    user: "Sarah Chen",
    action: "created agent",
    target: "Support Assistant",
    timestamp: "2026-09-10T10:00:00Z",
    tenant: "acme",
  },
  {
    id: "aud-002",
    user: "Jamik Tashpulatov",
    action: "approved",
    target: "appr-003",
    timestamp: "2026-09-12T08:30:00Z",
    tenant: "acme",
  },
  {
    id: "aud-003",
    user: "David Kim",
    action: "exported report",
    target: "cost-report-sept",
    timestamp: "2026-09-11T20:00:00Z",
    tenant: "globex",
  },
  {
    id: "aud-004",
    user: "Maria Garcia",
    action: "updated agent",
    target: "Content Writer",
    timestamp: "2026-09-10T14:00:00Z",
    tenant: "globex",
  },
  {
    id: "aud-005",
    user: "Sarah Chen",
    action: "rotated API key",
    target: "prod-key-1",
    timestamp: "2026-09-09T11:00:00Z",
    tenant: "acme",
  },
]

export const apiKeys: ApiKey[] = [
  {
    id: "key-001",
    name: "Production",
    key: "pk_live_9f2a...c4d1",
    scopes: ["agents:read", "sessions:read", "sessions:write"],
    createdAt: "2026-08-01T10:00:00Z",
    lastUsed: "2026-09-12T09:40:00Z",
    status: "active",
  },
  {
    id: "key-002",
    name: "Staging",
    key: "pk_test_3b7e...a9f0",
    scopes: ["agents:read"],
    createdAt: "2026-08-15T10:00:00Z",
    lastUsed: "2026-09-11T18:00:00Z",
    status: "active",
  },
  {
    id: "key-003",
    name: "Legacy",
    key: "pk_live_1c2d...e8b3",
    scopes: ["agents:read", "sessions:read"],
    createdAt: "2026-07-01T10:00:00Z",
    lastUsed: "2026-08-20T10:00:00Z",
    status: "revoked",
  },
]

export const kpiMetrics: KpiMetric[] = [
  {
    label: "Total Agents",
    value: "6",
    change: 12.5,
    changeLabel: "vs last week",
    trend: "up",
  },
  {
    label: "Active Sessions",
    value: "1,842",
    change: 8.2,
    changeLabel: "vs last week",
    trend: "up",
  },
  {
    label: "Completed Tasks",
    value: "3,214",
    change: 15.4,
    changeLabel: "vs last week",
    trend: "up",
  },
  {
    label: "Time Saved",
    value: "412h",
    change: 22.1,
    changeLabel: "vs last week",
    trend: "up",
  },
  {
    label: "API Cost",
    value: "$1,284",
    change: -3.6,
    changeLabel: "vs last week",
    trend: "down",
  },
]

export const alerts: AlertItem[] = [
  {
    id: "al-001",
    severity: "critical",
    title: "Escalation Router error",
    description: "Agent agt-004 failed to reach Zendesk API.",
    timestamp: "2026-09-12T09:20:00Z",
  },
  {
    id: "al-002",
    severity: "warning",
    title: "Budget at 82%",
    description: "Acme Corp monthly budget nearly consumed.",
    timestamp: "2026-09-12T08:00:00Z",
  },
  {
    id: "al-003",
    severity: "info",
    title: "Pending approval",
    description: "High-risk action awaiting review (appr-002).",
    timestamp: "2026-09-12T09:30:00Z",
  },
]

export const activityData = [
  { hour: "00:00", sessions: 12, tasks: 8, cost: 4 },
  { hour: "02:00", sessions: 8, tasks: 5, cost: 3 },
  { hour: "04:00", sessions: 15, tasks: 10, cost: 6 },
  { hour: "06:00", sessions: 42, tasks: 28, cost: 18 },
  { hour: "08:00", sessions: 120, tasks: 95, cost: 52 },
  { hour: "10:00", sessions: 210, tasks: 180, cost: 88 },
  { hour: "12:00", sessions: 185, tasks: 150, cost: 74 },
  { hour: "14:00", sessions: 240, tasks: 205, cost: 96 },
  { hour: "16:00", sessions: 198, tasks: 160, cost: 80 },
  { hour: "18:00", sessions: 130, tasks: 105, cost: 55 },
  { hour: "20:00", sessions: 75, tasks: 60, cost: 30 },
  { hour: "22:00", sessions: 40, tasks: 30, cost: 16 },
]

export const topAgents = [
  { name: "Support Assistant", sessions: 1842, cost: 221, satisfaction: 4.7 },
  { name: "Escalation Router", sessions: 2210, cost: 177, satisfaction: 4.0 },
  { name: "Billing Analyst", sessions: 640, cost: 288, satisfaction: 4.2 },
  { name: "Content Writer", sessions: 480, cost: 288, satisfaction: 4.5 },
  { name: "Data Pipeline Runner", sessions: 312, cost: 281, satisfaction: 3.9 },
]

export const agentStatusCounts: Record<AgentStatus, number> = {
  active: 2,
  idle: 1,
  error: 1,
  stalled: 1,
  archived: 1,
}

export const models = [
  "gpt-4o",
  "gpt-4",
  "gpt-4-turbo",
  "gpt-3.5-turbo",
  "claude-3-opus",
  "claude-3-sonnet",
]

export const teams = ["Support", "Finance", "Data", "Marketing", "Legal"]
export const domains = [
  "Customer Service",
  "Billing",
  "ETL",
  "Routing",
  "Content",
  "Compliance",
]
